sudo: required

services:
    - docker

# Install docker-ce to support multi stage builds
before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce

install:
    - docker-compose up --build -d
    - docker exec php-fpm composer install

script:
    - docker exec php-fpm composer run cs:check
    - docker exec php-fpm composer run test:unit

after_failure:
    - docker-compose php-fpm logs -f

after_script:
    - docker-compose down
