#!/usr/bin/env sh

set -a

COLOR_BLUE=
IMAGE_NAME=development
DB_USER=root
DB_PASS=root
DB_HOST=mysql
DB_PORT=3306
DB_BASE=default
APP_PORT=80
RANDOM_KEY=$(echo ${RANDOM}${RANDOM}${RANDOM}${RANDOM} | md5)

function help() { ### Show the list of possible functions
  grep -E '^function.*?###' $0 | sed "s/^function //g" | sed "s/()/:/g" | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-12s\033[0m %s\n", $1, $2}'
}

function dev() { ### build and start development environment
  docker-compose -f docker-compose-prod.yml -f docker-compose-dev.yml up --build
}

function down() { ### stop development environment
  docker-compose -f docker-compose-prod.yml -f docker-compose-dev.yml down
}

function tests() { ### run all tests (coding standards, static analysis, unit, integration)
  docker-compose -f docker-compose-prod.yml -f docker-compose-dev.yml exec php-fpm composer run tests
}

function prod() { ### build production images
  docker-compose -f docker-compose-prod.yml up --build
}

function logs() { ### show php-fpm errors
  docker-compose -f docker-compose-prod.yml php-fpm logs -f
}

function armageddon() { ### stop/delete all containers and delete all images
  docker stop $(docker ps -aq)
  docker rm $(docker ps -aq)
  docker rmi $(docker images -aq)
}

if [ "_$1" = "_" ]; then
  help
else
  "$@"
fi
