#!/bin/bash

set -a
source .env

function help() { ### Show the list of possible functions
  grep -E '^function.*?###' $0 | sed "s/^function //g" | sed "s/()/:/g" | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m./console %-12s\033[0m %s\n", $1, $2}'
}

function _compose() {
    docker-compose -f docker-compose-prod.yml -f docker-compose-dev.yml "$@"
}

function up() { ### build and start development environment
  _compose up --build
}

function upd() { ### build and start development environment detached
  _compose up --build --detach
}

function down() { ### stop development environment
  _compose down
}

function tests() { ### run all tests (coding standards, static analysis, unit, integration)
  _compose exec php-fpm composer run tests
}

function prod() { ### build production images
  docker-compose -f docker-compose-prod.yml up --build
}

function logs() { ### show php-fpm errors
  _compose exec php-fpm logs -f
}

function exec() { ### execute command on php-fpm container
  _compose exec php-fpm "$@"
}

function bash() { ### show php-fpm errors
  _compose exec "$1" bash
}

function armageddon() { ### stop/delete all containers and images (including any other project you had previously)
  echo -e $'\e[41m                                                                                      '
  echo '   This command will delete all images, including any other projects you might have   '
  echo -e $'                                                                                      \e[0m'
  echo

  read -p "Are you sure you want to continue? [y/n]" -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
      docker stop $(docker ps -aq)
      docker rm $(docker ps -aq)
      docker rmi $(docker images -aq)
  fi
}

if [ "_$1" = "_" ]; then
  help
else
  "$@"
fi
