version: '3'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: default
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        ports:
            - 3306:3306

    php-fpm:
        container_name: php-fpm
        image: devilbox/php-fpm:7.4-prod
        links:
            - mysql
        volumes:
            - ./:/var/www/html
            - .docker/.bashrc:/root/.bashrc
        build:
            context: .docker/php
        environment:
            APP_ENV: 'dev'
            APP_SECRET: '626bc82e64cf03896038999bd45fcc80'
            APP_DEBUG: 'true'
            DATABASE_URL: 'mysql://dev:dev@mysql:3306/project'

    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .docker/.bashrc:/root/.bashrc
        links:
            - php-fpm
        ports:
            - 80:80

