version: '3'
services:
    ### auth service
    php-fpm:
        container_name: php-fpm
        image: devilbox/php-fpm-7.4:latest
        volumes:
            - ./:/var/www/html
            - .docker/.bashrc:/root/.bashrc
        build:
            context: .docker/php
        environment:
            APP_ENV: 'dev'
            APP_SECRET: '626bc82e64cf03896038999bd45fcc80'
            APP_DEBUG: 'true'
            DATABASE_URL: 'sqlite:///%kernel.project_dir%/var/data.db'

    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - .docker/.bashrc:/root/.bashrc
        links:
            - php-fpm
        ports:
            - 80:80
