#!/usr/bin/env sh

set -e

echo "${DB_HOST}:3306"

# ./bin/wait-for "${DB_HOST}:3306" -- \
#     ./bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

# php -S 0.0.0.0:80 -t public/
