parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/*/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Framework\Controller\:
        resource: '../src/Framework/Controller'
        tags: ['controller.service_arguments']

    App\Framework\EventListener\ExceptionListener:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
